# Request
string goal_name             # 目标点名称
float32 speed               # 速度

---
# Result
# 响应是否成功以及消息
bool success            # 是否成功
string message          # 消息反馈
float64 total_time      # 总共用时

---
# Feedback
string current_name     #已到达的点
float64 time_spent      # 到达这个点用的时间
int32 index             # 这是第几个路径点