max_value: 180.0
min_value: -110.0

origin_param:
  back_origin_vel: 40.0
  find_origin_cnt: 2
  approix_origin_vel: 7.0
  approix_origin_step: 150.0
  origin_mode: 1
  origin_max_step: 1000

ctrl_param:
  kp: 0.25
  ti: 0.0
  td: 0.0
  max_acc: 800.0
  low_pass: 0.75
  ek: 5.0
  steady_clk: 10