rotary:
  pin: 4
  min_value: -120
  max_value: 180
  zero_duty: 24.729
  deg90_duty: 36.6

nod:
  pin: 1
  min_value: -40
  max_value: 180
  zero_duty: 16.907
  deg90_duty: 29.705

telescopic:
  pin: 2
  min_value: 0
  max_value: 18
  min_duty: 10
  max_duty: 47

gripper:
  pin: 3
  min_value: 0
  max_value: 28
  min_duty: 12.5
  max_duty: 41.0
  itinerary: 10.5