rotary:
  pin: 4
  min_value: -120
  max_value: 180
  zero_duty: 25.85
  deg90_duty: 37.8

nod:
  pin: 1
  min_value: -200
  max_value: 200
  zero_duty: 18.576
  deg90_duty: 30.966

telescopic:
  pin: 2
  min_value: 0
  max_value: 18
  min_duty: 10
  max_duty: 47

gripper:
  pin: 3
  min_value: 0
  max_value: 28
  min_duty: 12.5
  max_duty: 41.0
  itinerary: 10.5