rotary:
  pin: 4
  min_value: -190
  max_value: 100
  zero_duty: 35.66
  deg90_duty: 24

nod:
  pin: 1
  min_value: -95
  max_value: 90
  zero_duty: 30.4
  deg90_duty: 42

telescopic:
  pin: 2
  min_value: 0
  max_value: 18
  min_duty: 10
  max_duty: 50

gripper:
  pin: 3
  min_value: 0
  max_value: 28
  min_duty: 12.5
  max_duty: 41.0
  itinerary: 10.5