rotary:
  pin: 4
  min_value: -80
  max_value: 90
  zero_duty: 23.45
  deg90_duty: 11.3

nod:
  pin: 1
  min_value: -95
  max_value: 90
  zero_duty: 30.4
  deg90_duty: 11.3

telescopic:
  pin: 2
  min_value: 0
  max_value: 15
  min_duty: 17
  max_duty: 49

gripper:
  pin: 3
  min_value: 0
  max_value: 25
  min_duty: 12.5
  max_duty: 41.0
  itinerary: 10.5