#重置odometry

uint8 CLEAR_ALL = 0     #重置[x y theta]
uint8 CLEAR_POSE = 1    #重置[x y]
uint8 CLEAR_YAW = 2     #重置[theta]

uint8 clear_mode        #重置模式

#目标pose
float32 x
float32 y
float32 theta
---
bool success
