uint8 cmd # 指令 // 1:捕获图像 2:模型推理
string data # 预留
---
bool success    #成功标志
string[] label  # 类别标签
float32[] confidence  # 置信度
float32[] xmin  # 边界框 左
float32[] ymin  # 边界框 上
float32[] xmax  # 边界框 右
float32[] ymax  # 边界框 下