### ekf 配置文件 ###
ekf_filter_node:
  ros__parameters:
    # 滤波器输出位姿估计的频率，单位为 Hz。注意：滤波器在接收到至少一个输入消息之前不会开始计算。
    # 一旦接收到输入消息后，它将按照这里指定的频率持续运行，无论是否还有新的测量输入。如果未指定，默认值为 30。
    frequency: 10.0

    # ekf_localization_node 和 ukf_localization_node 都使用 3D 全向运动模型。
    # 如果此参数设置为 true，则状态估计中不会使用任何 3D 信息。
    # 如果你的机器人只在平面环境下运动，并且希望忽略由于地面轻微变化（例如 IMU 检测到的小幅震动）带来的影响，请启用此参数。
    # 如果未指定，默认值为 false。
    two_d_mode: true

    # 【高级设置】EKF 和 UKF 滤波器遵循标准的“预测-校正”循环。
    # 在预测阶段，如果没有加速度参考，t+1 时刻的速度会被简单预测为 t 时刻的速度。
    # 在校正阶段，这个预测值会与实际测量值融合，得到新的速度估计。
    # 这可能导致一个问题：最终的速度会变成“旧速度”和“新速度”的加权平均值。
    # 当这个速度进一步积分生成新的位姿时，可能会导致**收敛变慢**。
    # 这种现象在机器人转弯过程中（尤其使用激光雷达数据时）尤为明显。
    # 解决方法有：
    # 1. 增大该速度对应的过程噪声协方差（process_noise_covariance），降低对旧速度的信任；
    # 2. 减小该速度测量本身的测量协方差，提高对新测量值的信任。
    # 此外，用户也可以利用机器人运动控制命令作为预测阶段的“参考信息”：
    # 如果启用 use_control，滤波器会将控制命令转换为加速度项，用于预测阶段的计算。
    # 但请注意：**如果该状态量（如速度）已经通过其他传感器提供了加速度测量，滤波器会忽略控制命令中的加速度信息**。
    # 【功能】是否在预测阶段使用控制输入。默认值为 false。
    # 避免控制输入影响 EKF，与 AMCL 协作时推荐关闭
    use_control: false

    # 是否发布加速度状态。如果未指定，默认值为 false。
    publish_acceleration: false

    # 是否通过 /tf 话题广播坐标变换。如果未指定，默认值为 true。
    publish_tf: true

    # 1. 将 map_frame、odom_frame 和 base_link_frame 设置为系统中对应的坐标系名称。
    #     1a. 如果你的系统没有 map_frame，只需移除该参数，并确保 "world_frame" 设置为 odom_frame 的值。
    # 2. 如果你融合的是连续位置信息（例如轮速计里程计、视觉里程计或 IMU 数据），请将 "world_frame" 设置为 odom_frame 的值。
    #    这是 robot_localization 状态估计节点的默认行为。
    # 3. 如果你融合的是带有离散跳变的全局绝对位置信息（例如 GPS 或地标观测得到的位置更新），那么：
    #     3a. 将 "world_frame" 设置为 map_frame 的值。
    #     3b. 确保系统中有其他节点生成 odom->base_link 的坐标变换。注意：这个节点可以是另一个 robot_localization 的状态估计节点！
    #         但是，该节点不能融合全局数据。
    map_frame: map              # 如果未指定，默认值为 "map"
    odom_frame: odom            # 如果未指定，默认值为 "odom"
    base_link_frame: base_link  # 如果未指定，默认值为 "base_link"
    world_frame: odom           # 如果未指定，默认值为 odom_frame 的值

    odom0: /chassis/odom/raw
    odom0_config: [false, false, false,     # 位置 [x, y, z] → 不用
                   false, false, false,     # 姿态 [roll, pitch, yaw] → 不用
                   true,  true,  false,     # 线速度 [vx, vy, vz] → 用 X 和 Y → 差速驱动重要
                   false, false, true,      # 角速度 [roll rate, pitch rate, yaw rate] → 用 Z → 差速驱动转向用
                   false, false, false]     # 加速度 [ax, ay, az] → 不用

#    imu0: /vmxpi/imu
#    imu0_config: [false, false, false,     # 位置 [x, y, z] → 不用
#                  false, false, true,      # 姿态 [roll, pitch, yaw] → 用 yaw → 提供航向角（姿态）
#                  false, false, false,     # 线速度 [vx, vy, vz] → 不用
#                  false, false, true,      # 角速度 [roll rate, pitch rate, yaw rate] → 用 Z → 角速度由 IMU 提供
#                  true,  false, false]     # 加速度 [ax, ay, az] → 用 X → 提供线加速度
