correction_odom:
  ros__parameters:
    use_sim_time: False

    correction_service: /correction_odom
    robot_data_topic: /web_transform_node/robot_data
    set_odom_service: /chassis/reset_odom
    waypoints_topic: /waypoints

find_nearest_waypoint:
  ros__parameters:
    use_sim_time: False

    find_nearest_waypoint_topic: /find_nearest_waypoint
    robot_data_topic: /web_transform_node/robot_data
    waypoints_topic: /waypoints

    angle_threshold: 30

pub_waypoints:
  ros__parameters:
    use_sim_time: False

    waypoints_path: 国赛路径点b.yaml
    waypoints_topic: /waypoints

generate_path:
  ros__parameters:
    use_sim_time: False

    waypoints_topic: /waypoints
    generate_path_service: /generate_path

navigation_to_waypoint:
  ros__parameters:
    use_sim_time: False

    robot_data_topic: /web_transform_node/robot_data
    set_odom_service: /chassis/reset_odom
    navigation_to_waypoint_action: /navigation_to_waypoint
    generate_path_service: /generate_path
    correction_service: /correction_odom
    find_nearest_waypoint_service: /find_nearest_waypoint
    navigation_action: /nav2_action

    speed: 0.6
    uphill_offset: 0.15
    reverse_uphill: True
    distance_threshold: 0.05
    skip_start_point_correction: c_start
